apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-sts-headers
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      Upgrade: "websocket"
      Connection: "Upgrade"

---
# 1. Основной сайт (заглушка)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-web
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.domain }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}
          port: 80
  tls:
    certResolver: le

---
# 2. Обработка WebSocket (Path routing)
{{- range .Values.inbounds }}
{{- if eq .mode "ingress-path" }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $.Values.domain }}`) && PathPrefix(`{{ .path }}`)
      kind: Rule
      middlewares:
        - name: {{ $.Release.Name }}-sts-headers
      services:
        - name: {{ $.Release.Name }}
          port: {{ .port }}
          passHostHeader: true # Критично: передаем Host как есть в Xray
  tls:
    certResolver: le
---
{{- end }}
{{- end }}

# 3. Обработка Reality/Trojan (SNI Routing)
{{- range .Values.inbounds }}
{{- if eq .mode "ingress-sni" }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ range $i, $d := .sni }}{{ if $i }} || {{ end }}HostSNI(`{{ $d }}`){{ end }}
      services:
        - name: {{ $.Release.Name }}
          port: {{ .port }}
          # proxyProtocol удален, так как в панели Xray он выключен!
  tls:
    passthrough: true
---
{{- end }}
{{- end }}