# 1. HTTPS для сайта
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-web
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.domain }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}
          port: 80
  tls:
    certResolver: le

---
# 2. TCP Passthrough для Reality
# Генерируем IngressRouteTCP только для инбаундов с mode: ingress
{{- range .Values.inbounds }}
{{- if eq .mode "ingress" }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  entryPoints:
    - websecure # Слушаем на 443
  routes:
    # Собираем все домены SNI через OR (||)
    - match: {{ range $i, $d := .sni }}{{ if $i }} || {{ end }}HostSNI(`{{ $d }}`){{ end }}
      services:
        - name: {{ $.Release.Name }}
          port: {{ .port }}
  tls:
    passthrough: true
---
{{- end }}
{{- end }}